### PR TITLE
This change adds the response body output when an error occurs. 

### PR DESCRIPTION
**Pull request by ctennis**
As is, if there is a problem with the auth flow, it's not obvious what the issue might be beyond a generic "400" error response. In our case the swallowed error was:

 {"error":"invalid_grant","error_description":"The application's assurance requirements are not met by the 'subject_token'."}

This just adds that to the output.

This also does a small restructure to make sure we're closing the response body per golang guidelines.

### CODE REVIEW

**Comment by nickgamb** [comment]
This looks good to me pending review from @MikeMondragon-okta

**Review by MikeMondragon-okta — APPROVED** [review]
Awesome, thanks @ctennis

**Comment by monde** [comment]
PR has QC errors, I need to have GH action QC merges.
https://github.com/okta/okta-aws-cli/actions/runs/3707041401/jobs/6282977995

**Comment by monde** [comment]
https://github.com/chenrui333/github-action-test/pull/33/files#diff-a9e79319d155d481a02d7ee4039bf11a8c8ada48e7adbf0e1bf01949744b08d4R3

**Comment by monde** [comment]
[GA v0.1.0](https://github.com/okta/okta-aws-cli/releases/tag/v0.1.0) has been released 🎉

**Pull request merged**
