### PR TITLE
If an idp/role is specified at the CLI, or there is only one anyway then choose it by default

### PR DESCRIPTION
**Pull request by ctennis**

### CODE REVIEW

**Comment by ctennis** [comment]
Fixes #24

**Comment by nickgamb** [comment]
More functionality is already planned here to support multiple AWS environments and profiles.

**Comment by monde** [comment]
I like this PR. Originally I intended `AWS_IAM_IDP` and `AWS_IAM_ROLE` to be presets on the selector but this changes that functionality to skip the selection if you already know your IdP and Role ARNs. That's cool. I'm working on supporting multiple AWS environments fully and this PR will cause a minor merge conflict. That said, I'll pull in this PR so @ctennis gets on the contributor list.

**Review by MikeMondragon-okta — APPROVED** [review]
🎉

**Comment by monde** [comment]
[GA v0.1.0](https://github.com/okta/okta-aws-cli/releases/tag/v0.1.0) has been released 🎉

**Pull request merged**
