### PR TITLE
Add token expiration value to written credentials

### PR DESCRIPTION
**Pull request by tim-fitzgerald**
This PR ensures that the Expiration value for the temporary AWS credentials is written to the credentials object. This allows automated checking for expired credentials in dependent tools.

### CODE REVIEW

**Comment by monde** [comment]
Thanks @tim-fitzgerald . Can you update the README with info about `x_security_token_expires` being written to the AWS creds file and how it might be utilized.

@jefftaylor-okta I believe this is a feature from https://github.com/Versent/saml2aws . Seems to be a nice to have. @tim-fitzgerald did the work and explained the use case.

**Comment by tim-fitzgerald** [comment]
@monde added a note in the README.

To be more explicit about our specific use case, we have an internal developer tool that aims to keep our devs environments in a good state at all times. Part of its diagnostics is to check for valid AWS credentials and refresh them if expired. And as you have noted, this is a parity feature with saml2aws.

**Comment by JohnPaton** [comment]
Any chance of this getting merged before 1.0?

**Comment by tim-fitzgerald** [comment]
Sorry just noticed failing CI. Will fix that first

**Comment by tim-fitzgerald** [comment]
Gonna bump this once again folks. This is the final blocking issue we have for utilising this tool at our Org and would really be impactful for us if we can get it merged and a point release cut for it.

**Comment by monde** [comment]
I'll defer to our PM @jefftaylor-okta if we'll take this PR. Appending `x_NAME` name / value pairs into a profile within an AWS creds file is not a technique prescribed by the AWS CLI itself (nothing is documented about it at https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html ). It is a practice that fell out of the saml2aws community https://github.com/Versent/saml2aws . Accepting this PR implies we believe in supporting this practice and accept responsibility for taking on this contract.

**Comment by monde** [comment]
I hear you @tim-fitzgerald , community practices is a good justification to take on `x_NAME` name/value pairs in a creds file profile. Also, we want to support caching the device grant token so that the browser only has to be popped once for a device grant and then multiple profiles and associated roles can be established thereafter as discussed in #74 . We'd have to do that in in the AWS creds file or a dedicated config file for okta-aws-cli. I will discuss further with @jefftaylor-okta

**Comment by jefftaylor-okta** [comment]
@tim-fitzgerald, Hey, this is the PM for the Okta's AWS CLI. Thanks for this PR! Looking at the parity between `saml2aws` and `aws-gimme-creds`, this seems like a very reasonable proposal to aid in the migration between tools. @JohnPaton I do not think this will make it into 1.0, but we will look into getting it in soon after.

**Comment by tim-fitzgerald** [comment]
@jefftaylor-okta thanks for the info. Do we have a timeline for 1.0? As I mentioned, this is a blocker for us right now and would be great if we could tie our internal issues to a rough timeline.

**Pull request closed without merging**
