### PR TITLE
Adding the cmd to list profiles in ~/.okta/okta.yaml

### PR DESCRIPTION
**Pull request by pmgalea**
Adding a new command _list-profiles_ to list profiles

### CODE REVIEW

**Review by monde — CHANGES_REQUESTED** [review]
Thanks @pmgalea 
Can you add `list-profiles` as the fourth row in the commands table in the README? After the `m2m` row and before the `debug` row.

**Review by monde — APPROVED** [review]

**Review by monde — CHANGES_REQUESTED** [review]
@pmgalea we have merge protections on all commits being signed. Can you update your PR with signed commits?

- Set up: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
- Rewriting old commits with your new signature: https://superuser.com/questions/397149/can-you-gpg-sign-old-commits

**Comment by monde** [comment]
@pmgalea are you sure you want to close this PR?
I was looking at `yq` and it is also useful:
```
$ cat ~/.okta/okta.yaml | yq '.awscli.profiles | keys'
- staging
- production
```

**Comment by pmgalea** [comment]
Yeah I have another PR coming as I still cannot get my commit verified.  No idea why as i've loaded my keys in github and signed the commits

**Pull request closed without merging**
