### PR TITLE
refactor: Rename internal package to pkg

### LINKED ISSUE #57: Rename `internal` package to `pkg`
Thinking about having our internal CLI move from saml2aws to okta-aws-cli, but everything we'd need from `okta-aws-cli` is hidden in the `internal` package.

Would it be possible to rename the `internal` package to `pkg` so that the internal functions, variables and types can be exported?

I don't mind making a PR for it myself.

### PR DESCRIPTION
**Pull request by TwiN**
Fixes #57

### CODE REVIEW

**Comment by monde** [comment]
@TwiN the only public method on `sessiontoken.SessionToken` is `EstablishToken()` and there is the idiomatic constructor function `NewSessionToken()` in that package. I'm not following how this would be useful to you. `EstablishToken()` just kicks off the behavior of okta-aws-cli as an application. It isn't really exposing an general purpose interface as an SDK. If you could elaborate on the use case would be very helpful.

**Comment by TwiN** [comment]
@monde I presume I will likely need access to `internal/config/config.go`'s `Config` alongside the methods you mentioned, though as you've pointed out, further changes may be required -- did you want me to make both of these changes as part of the same PR?

**Comment by monde** [comment]
@TwiN I'm still not seeing how making sessiontoken a public package is useful in that the methods that are surfaced are representative of an application and don't have generic SDK-like signatures. Can you explain to me how moving the package from internal to pkg will be useful to you? 

Presently does `make test` pass for this PR?

**Comment by TwiN** [comment]
@monde `make test` does currently pass on my machine, yes.

> I'm still not seeing how making sessiontoken a public package is useful in that the methods that are surfaced are representative of an application and don't have generic SDK-like signatures. Can you explain to me how moving the package from internal to pkg will be useful to you?

Currently, replicating calling `okta-aws-cli` from the command prompt through a library would be done by calling `cmd/root/root.go`'s `Execute()` command, which calls `buildRootCommand()` and subsequently `cmd.Execute()`.

Instead of doing this, which would automatically use viper for configuration management, I'd like to create my own `Config` variable (with parameters that are not handled through viper), which I'd pass onto `SessionToken` and then call `SessionToken`'s `EstablishToken()` method. Unfortunately, the `Config` and the `SessionToken` structs are part of the `internal` package, which is not accessible from other libraries.

To retrieve the output AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_SESSION_TOKEN, I'll need to make another change since right now, the only options configurable are AWS' credentials file and through environment variables printed using `fmt.Printf`, but I figured it would be a better idea to just start with renaming `internal` to `pkg` instead of making many changes at once.

**Comment by monde** [comment]
@TwiN I'm not agreeing with this PR. okta-aws-cli is an app, if we turn parts of it into a public SDK then we are taking on an additional contract with the community about the usage of this code. That is not our intention. There was a recent blog post that discusses project layout which better explains this thinking https://appliedgo.com/blog/go-project-layout

**Comment by TwiN** [comment]
@monde I see. That's unfortunate, but I respect your decision! I'll close the PR

**Pull request closed without merging**
