### PR TITLE
Be smarter about the INI style credentials file so we don't just append indefinitely

### PR DESCRIPTION
**Pull request by ctennis**

### CODE REVIEW

**Comment by ctennis** [comment]
Fixes #23

**Comment by nickgamb** [comment]
The goal is to not use the credentials file at all - instead keeping credentials in memory.

**Comment by monde** [comment]
Thanks @ctennis . (re)Writing the creds file needs to be behind a CLI flag so the operator has to explicitly declare they want that functionality. I don't want to be responsible for corrupting a credentials file inadvertently. I know people can have a creds file with hundreds+ of lines including comments. I'll have to invest some time looking at the INI package to see if itencapsulates the behavior I'd expect - that only the portion of the declared profile is changed and that every other profile including comments is not changed.

Also, as @nickgamb points out, we don't want to be managing credentials to disk, even if they are short lived, that is why we prefer to ENV variables. So if the operator wants to do work flows that we don't believe in, like writing to credentials file, we'll try to support those features when we can but they have to be gated behind a CLI flag.

`--write-creds` seems to be a good CLI flag name for this feature.

```
  -w, --aws-credentials string       Path to AWS credentials file, only valid with format "aws-credentials" (default "/user/.aws/credentials")
  -z, --write-creds                  Write to AWS credentials file instead of appening
  -f, --format string                Output format. [env-var|aws-credentials] (default "env-var")
```

**Review by MikeMondragon-okta — CHANGES_REQUESTED** [review]
Writing the creds file needs to be gated behind a CLI flag `--write-creds` or similar descriptive name.

It needs to be verified that the INI package does not modify any profiles other than the one targeted.

**Acceptable**
Before for profile test1
```
# [default]
# aws_access_key_id     = aaa
# aws_secret_access_key = bbb
# aws_session_token     = ccc

[test1]
aws_access_key_id = A..
aws_secret_access_key = B...
aws_session_token     = C...

[test2]
aws_access_key_id = X...
aws_secret_access_key = Y...
aws_session_token     = Z...
```
After
```
# [default]
# aws_access_key_id     = aaa
# aws_secret_access_key = bbb
# aws_session_token     = ccc

[test1]
aws_access_key_id = D..
aws_secret_access_key = E...
aws_session_token     = F...

[test2]
aws_access_key_id = X...
aws_secret_access_key = Y...
aws_session_token     = Z...
```

**Unacceptable**
Before
```
# [default]
# aws_access_key_id     = aaa
# aws_secret_access_key = bbb
# aws_session_token     = ccc

[test1]
aws_access_key_id = A..
aws_secret_access_key = B...
aws_session_token     = C...

[test2]
aws_access_key_id = X...
aws_secret_access_key = Y...
aws_session_token     = Z...
```

After
Comments removed, profile ordering changed, any text other than the targeted lines change, etc..
```
[test2]
aws_access_key_id = X...
aws_secret_access_key = Y...
aws_session_token     = Z...

[test1]
aws_access_key_id = D..
aws_secret_access_key = E...
aws_session_token     = F...
```

**Comment by monde** [comment]
Looking at the INI repo there have been a number of issues and PRs related to AWS creds file throughout the life of the project https://github.com/go-ini/ini/issues?q=aws

**Comment by ctennis** [comment]
Totally understand, happy to add tests if that's helpful. The main driver for the PR is that the existing code there now which writes to the credentials file just appends to the end, and this breaks the AWS cli as it doesn't know what to do if more than one profile of the same name exists in the file.

**Comment by monde** [comment]
[GA v0.1.0](https://github.com/okta/okta-aws-cli/releases/tag/v0.1.0) has been released 🎉

**Pull request closed without merging**
